export { default as Copy } from "./Copy"
export { default as Success } from "./Success"
export { default as Arrow } from "./Arrow"
export { default as Pencil } from "./Pencil"
export { default as Bookmark } from "./Bookmark"

export { default as Mail } from "./Mail"
export { default as Github } from "./Github"
export { default as Youtube } from "./Youtube"
export { default as Twitter } from "./Twitter"
export { default as Linkedin } from "./Linkedin"
export { default as Facebook } from "./Facebook"
