export { default as CategoryBackground } from "./Category"
export { default as PostBackground } from "./Post"
export { default as HomeBackground } from "./Home"
export { default as ProfileBackground } from "./Profile"
export { default as SVGContainer } from "../common/background.container"
